import { sql } from 'drizzle-orm';
import { pgEnum, timestamp, uuid } from 'drizzle-orm/pg-core';
import {
  AGE_RATINGS,
  AVAILABILITY_STATUSES,
  BLOG_POST_STATUSES,
  CATALOGUE_PROPOSAL_STATUSES,
  CATALOGUE_PROPOSAL_TARGET_TYPES,
  CONTACT_MESSAGE_DIRECTIONS,
  CONTACT_MESSAGE_STATUSES,
  DEVICE_STATUSES,
  DEVICE_TYPES,
  ENTRY_RELATION_SOURCES,
  ENTRY_RELATION_TYPES,
  ENTRY_TYPES,
  EPISODE_TYPES,
  MEDIA_ASSET_KINDS,
  MEDIA_PROVIDER_IDS,
  MODERATION_ACTIONS,
  ORGANIZATION_ROLES,
  QUALITY_HINTS,
  REACTION_KINDS,
  RELEASE_STATUSES,
  REPORT_STATUSES,
  REPORT_TARGET_TYPES,
  REPORT_TYPES,
  SEASONS_OF_YEAR,
  SOURCE_KINDS,
  SOURCE_LANGUAGES,
  SOURCE_STATUSES,
  TITLE_KINDS,
  TRANSLATOR_ROLES,
  USER_ROLES,
  WATCH_STATUSES,
} from '@playanime/contracts';

/**
 * Shared column builders and enum declarations.
 *
 * Enums are declared from the `@playanime/contracts` constants rather than
 * re-listed here. A Postgres enum and a TypeScript union that drift apart
 * produce runtime insert failures that type checking cannot catch, so there is
 * exactly one list and the database derives from it.
 */

/** Drizzle's pgEnum needs a non-empty tuple; contracts export plain arrays. */
const asTuple = <T extends string>(values: readonly T[]): [T, ...T[]] => {
  const [first, ...rest] = values;
  if (first === undefined) throw new Error('Enum must declare at least one value.');
  return [first, ...rest];
};

/* -------------------------------------------------------------------------- */
/* Enums                                                                       */
/* -------------------------------------------------------------------------- */

export const userRoleEnum = pgEnum('user_role', asTuple(USER_ROLES));
export const entryTypeEnum = pgEnum('entry_type', asTuple(ENTRY_TYPES));
export const entryRelationTypeEnum = pgEnum('entry_relation_type', asTuple(ENTRY_RELATION_TYPES));
export const entryRelationSourceEnum = pgEnum('entry_relation_source', asTuple(ENTRY_RELATION_SOURCES));
export const episodeTypeEnum = pgEnum('episode_type', asTuple(EPISODE_TYPES));
export const releaseStatusEnum = pgEnum('release_status', asTuple(RELEASE_STATUSES));
export const seasonOfYearEnum = pgEnum('season_of_year', asTuple(SEASONS_OF_YEAR));
export const ageRatingEnum = pgEnum('age_rating', asTuple(AGE_RATINGS));
export const titleKindEnum = pgEnum('title_kind', asTuple(TITLE_KINDS));
export const organizationRoleEnum = pgEnum('organization_role', asTuple(ORGANIZATION_ROLES));
export const mediaAssetKindEnum = pgEnum('media_asset_kind', asTuple(MEDIA_ASSET_KINDS));
export const watchStatusEnum = pgEnum('watch_status', asTuple(WATCH_STATUSES));
export const reactionKindEnum = pgEnum('reaction_kind', asTuple(REACTION_KINDS));
export const translatorRoleEnum = pgEnum('translator_role', asTuple(TRANSLATOR_ROLES));

export const mediaProviderEnum = pgEnum('media_provider', asTuple(MEDIA_PROVIDER_IDS));
export const sourceStatusEnum = pgEnum('source_status', asTuple(SOURCE_STATUSES));
export const sourceKindEnum = pgEnum('source_kind', asTuple(SOURCE_KINDS));
export const sourceLanguageEnum = pgEnum('source_language', asTuple(SOURCE_LANGUAGES));
export const qualityHintEnum = pgEnum('quality_hint', asTuple(QUALITY_HINTS));
export const availabilityStatusEnum = pgEnum('availability_status', asTuple(AVAILABILITY_STATUSES));

export const reportTypeEnum = pgEnum('report_type', asTuple(REPORT_TYPES));
export const reportTargetTypeEnum = pgEnum('report_target_type', asTuple(REPORT_TARGET_TYPES));
export const reportStatusEnum = pgEnum('report_status', asTuple(REPORT_STATUSES));
export const moderationActionEnum = pgEnum('moderation_action', asTuple(MODERATION_ACTIONS));

export const catalogueProposalTargetTypeEnum = pgEnum(
  'catalogue_proposal_target_type',
  asTuple(CATALOGUE_PROPOSAL_TARGET_TYPES),
);
export const catalogueProposalStatusEnum = pgEnum(
  'catalogue_proposal_status',
  asTuple(CATALOGUE_PROPOSAL_STATUSES),
);

export const deviceTypeEnum = pgEnum('device_type', asTuple(DEVICE_TYPES));
export const deviceStatusEnum = pgEnum('device_status', asTuple(DEVICE_STATUSES));

export const contactMessageStatusEnum = pgEnum('contact_message_status', asTuple(CONTACT_MESSAGE_STATUSES));
export const contactMessageDirectionEnum = pgEnum(
  'contact_message_direction',
  asTuple(CONTACT_MESSAGE_DIRECTIONS),
);

export const blogPostStatusEnum = pgEnum('blog_post_status', asTuple(BLOG_POST_STATUSES));

/* -------------------------------------------------------------------------- */
/* Column helpers                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Primary key.
 *
 * UUIDv4 generated by the database. Random ids avoid leaking row counts and
 * creation order through the API, and let a client generate an id before an
 * insert when it needs to. The index-locality cost of random UUIDs is real but
 * acceptable at this scale; moving to UUIDv7 later is a default change, not a
 * type change.
 */
export const primaryId = () => uuid('id').primaryKey().defaultRandom();

/** Foreign-key column. Named explicitly at the call site, e.g. `fk('user_id')`. */
export const fk = (name: string) => uuid(name);

/** `timestamptz` everywhere. A naive timestamp is a bug waiting for a DST boundary. */
export const createdAt = () =>
  timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow();

/**
 * Updated-at maintained by the database.
 *
 * `$onUpdate` keeps it correct for Drizzle writes, and the column default
 * covers rows touched by migrations or manual SQL.
 */
export const updatedAt = () =>
  timestamp('updated_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/** Standard created/updated pair. */
export const timestamps = () => ({
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

/**
 * Soft-delete marker.
 *
 * Used where moderation or audit history must survive removal. A nullable
 * timestamp rather than a boolean, so *when* it happened is recorded too.
 */
export const deletedAt = () => timestamp('deleted_at', { withTimezone: true, mode: 'date' });

/** Case-insensitive uniqueness helper for citext-like columns. */
export const lower = (column: unknown) => sql`lower(${column})`;
