import { relations } from 'drizzle-orm';
import { index, pgTable, timestamp, uniqueIndex, varchar } from 'drizzle-orm/pg-core';
import { deviceStatusEnum, deviceTypeEnum, fk, primaryId, timestamps } from './_shared.js';
import { users } from './users.js';

/**
 * Registered devices, for account-level session/device management.
 *
 * Deliberately separate from `trusted_devices` (`auth.ts`): that table has a
 * narrow, short-lived purpose — skipping the 2FA prompt for a while — with no
 * display name, no status, no revoke/list UI. This table is the durable,
 * user-facing "where is my account signed in" identity, independent of 2FA.
 *
 * `deviceId` is generated by the client (a UUID kept in localStorage, not a
 * fingerprint) and sent on login/register; it is distinct from this row's own
 * `id`, since a client-supplied value is never trusted as a primary key.
 * Uniqueness is scoped to `(userId, deviceId)` — the same browser logging into
 * two different accounts is legitimately two device rows, not a collision.
 */
export const userDevices = pgTable(
  'user_devices',
  {
    id: primaryId(),
    userId: fk('user_id')
      .references(() => users.id, { onDelete: 'cascade' })
      .notNull(),

    deviceId: varchar('device_id', { length: 128 }).notNull(),

    /** User-editable ("Gaming PC"); null until the user sets one. */
    displayName: varchar('display_name', { length: 100 }),

    deviceType: deviceTypeEnum('device_type').notNull().default('unknown'),
    /** Parsed from the user agent at sighting time, refreshed opportunistically. */
    browser: varchar('browser', { length: 64 }),
    os: varchar('os', { length: 64 }),

    /**
     * Separate from any one session's revoked/expired state — blocking a
     * device is an account-owner action independent of a single session's
     * lifecycle.
     */
    status: deviceStatusEnum('status').notNull().default('active'),

    firstSeenAt: timestamp('first_seen_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),

    blockedAt: timestamp('blocked_at', { withTimezone: true, mode: 'date' }),
    blockedReason: varchar('blocked_reason', { length: 64 }),

    ...timestamps(),
  },
  (table) => [
    uniqueIndex('user_devices_user_device_key').on(table.userId, table.deviceId),
    // The device list screen: "this user's devices, active first, most recent first."
    index('user_devices_user_status_idx').on(table.userId, table.status, table.lastSeenAt),
  ],
);

export const userDevicesRelations = relations(userDevices, ({ one }) => ({
  user: one(users, { fields: [userDevices.userId], references: [users.id] }),
}));

export type UserDeviceRow = typeof userDevices.$inferSelect;
export type NewUserDeviceRow = typeof userDevices.$inferInsert;
