/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/admin/dashboard': RouteRecordInfo<
      '/admin/dashboard',
      '/admin/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/anime/[slug]': RouteRecordInfo<
      '/anime/[slug]',
      '/anime/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/browse': RouteRecordInfo<
      '/browse',
      '/browse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalogue/create': RouteRecordInfo<
      '/catalogue/create',
      '/catalogue/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalogue/manage/[slug]': RouteRecordInfo<
      '/catalogue/manage/[slug]',
      '/catalogue/manage/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/legal/[page]': RouteRecordInfo<
      '/legal/[page]',
      '/legal/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/[username]': RouteRecordInfo<
      '/profile/[username]',
      '/profile/:username',
      { username: ParamValue<true> },
      { username: ParamValue<false> },
      | never
    >,
    '/profile/me': RouteRecordInfo<
      '/profile/me',
      '/profile/me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search': RouteRecordInfo<
      '/search',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/translator/[slug]': RouteRecordInfo<
      '/translator/[slug]',
      '/translator/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/translator/create': RouteRecordInfo<
      '/translator/create',
      '/translator/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/translator/dashboard/[slug]': RouteRecordInfo<
      '/translator/dashboard/[slug]',
      '/translator/dashboard/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/translators': RouteRecordInfo<
      '/translators',
      '/translators',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/trending': RouteRecordInfo<
      '/trending',
      '/trending',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/watch/[episodeId]': RouteRecordInfo<
      '/watch/[episodeId]',
      '/watch/:episodeId',
      { episodeId: ParamValue<true> },
      { episodeId: ParamValue<false> },
      | never
    >,
    '/watchtogether/sessions': RouteRecordInfo<
      '/watchtogether/sessions',
      '/watchtogether/sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/views/admin/dashboard.vue': {
      routes:
        | '/admin/dashboard'
      views:
        | never
    }
    'src/views/anime/[slug].vue': {
      routes:
        | '/anime/[slug]'
      views:
        | never
    }
    'src/views/browse.vue': {
      routes:
        | '/browse'
      views:
        | never
    }
    'src/views/catalogue/create.vue': {
      routes:
        | '/catalogue/create'
      views:
        | never
    }
    'src/views/catalogue/manage/[slug].vue': {
      routes:
        | '/catalogue/manage/[slug]'
      views:
        | never
    }
    'src/views/legal/[page].vue': {
      routes:
        | '/legal/[page]'
      views:
        | never
    }
    'src/views/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/views/profile/[username].vue': {
      routes:
        | '/profile/[username]'
      views:
        | never
    }
    'src/views/profile/me.vue': {
      routes:
        | '/profile/me'
      views:
        | never
    }
    'src/views/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/views/search.vue': {
      routes:
        | '/search'
      views:
        | never
    }
    'src/views/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/views/translator/[slug].vue': {
      routes:
        | '/translator/[slug]'
      views:
        | never
    }
    'src/views/translator/create.vue': {
      routes:
        | '/translator/create'
      views:
        | never
    }
    'src/views/translator/dashboard/[slug].vue': {
      routes:
        | '/translator/dashboard/[slug]'
      views:
        | never
    }
    'src/views/translators.vue': {
      routes:
        | '/translators'
      views:
        | never
    }
    'src/views/trending.vue': {
      routes:
        | '/trending'
      views:
        | never
    }
    'src/views/watch/[episodeId].vue': {
      routes:
        | '/watch/[episodeId]'
      views:
        | never
    }
    'src/views/watchtogether/sessions.vue': {
      routes:
        | '/watchtogether/sessions'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
